# Generated by Django 3.1.4 on 2021-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210223_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoinstancia',
            name='agendamentoData',
            field=models.DateField(null=True, verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='agendamentoinstancia',
            name='agendamentoHorario',
            field=models.TimeField(null=True, verbose_name='Horário:'),
        ),
    ]
