# Generated by Django 3.1.4 on 2021-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210223_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentoinstancia',
            name='agendamentoData',
        ),
        migrations.AlterField(
            model_name='agendamentoinstancia',
            name='agendamentoHorario',
            field=models.TimeField(default=1, verbose_name='Horário:'),
            preserve_default=False,
        ),
    ]
